application: metaboxoffice
version: 1
runtime: python
api_version: 1

handlers:
- url: /LookupLocation
  script: main.py

- url: /LookupMovieListings
  script: main.py

- url: /LookupTrailerListings
  script: main.py

#- url: .*
#  script: main.py
